parameters:
#    ma_dev_twig.example.class: MaDev\TwigBundle\Example

services:
#    ma_dev_twig.example:
#        class: %ma_dev_twig.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
