madev_voyages:
    resource: "@MaDevVoyagesBundle/Resources/config/routing.yml"
    prefix:   /

madev_upload:
    resource: "@MaDevUploadFileBundle/Resources/config/routing.yml"
    prefix:   /admin/
