parameters:
#    ma_dev_user.example.class: MaDev\UserBundle\Example

services:
#    ma_dev_user.example:
#        class: %ma_dev_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
