voyages_country_index:
    pattern: /pays
    defaults: { _controller: MaDevVoyagesBundle:Country:index }

voyages_city_index:
    pattern: /ville
    defaults: { _controller: MaDevVoyagesBundle:City:index }