madev_voyages_admin:
    resource: "@MaDevVoyagesBundle/Resources/config/admin/routing.yml"
    prefix:   /admin/

madev_voyages_front:
    resource: "@MaDevVoyagesBundle/Resources/config/front/routing.yml"
    prefix:   /