parameters:
#    ma_dev_voyages.example.class: MaDev\VoyagesBundle\Example

services:
#    ma_dev_voyages.example:
#        class: %ma_dev_voyages.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
