uploadfile_file_index:
    pattern: /fichiers
    defaults: { _controller: "MaDevUploadFileBundle:File:index" }

uploadfile_file_upload:
    pattern: /upload
    defaults: { _controller: "MaDevUploadFileBundle:File:upload" }
    
uploadfile_file_update:
    pattern: /{id}/update
    defaults: { _controller: "MaDevUploadFileBundle:File:update" }
