uploadfile_file_index:
    pattern: /fichiers
    defaults: { _controller: "MaDevUploadFileBundle:File:index" }

uploadfile_file_upload:
    pattern: /uploader
    defaults: { _controller: "MaDevUploadFileBundle:File:upload" }
