parameters:
#    ma_dev_upload_file.example.class: MaDev\UploadFileBundle\Example

services:
#    ma_dev_upload_file.example:
#        class: %ma_dev_upload_file.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
